# Generated by Django 3.2.6 on 2022-06-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
