# Generated by Django 3.2.6 on 2022-06-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=12)),
                ('thumbnail', models.CharField(max_length=64)),
                ('title', models.TextField()),
            ],
        ),
    ]
